---
repo-name: peripherals-rackspace
categories:
- Cloud
- DevOps
display-name: Rackspace
manufacture: Rackspace
product: 
description: Managed cloud provider with tailored solutions on many popular hosting platforms such as VMware, AWS, Azure, OpenStack, and many more.
