---
repo-name: peripherals-rackspace
categories:
- Cloud
- DevOps
display-name: Rackspace
manufacture: Rackspace
product: 
description: This service is a managed cloud provider with tailor solutions on many popular hosting platforms such as: VMware, AWS, Microsoft Cloud / Azure, OpenStack, and many more.
